#!/bin/bash
#
# regenerate hd-idle config based on currently attached USB HDDs
#
# for installation run:
# 0) apt install hd-idle -y # or similar
# 1) to run this script when a new device is attached
# sudo nano /etc/udev/rules.d/99-hd-idle.rules
# ACTION=="add|remove", SUBSYSTEM=="block", ENV{ID_BUS}=="usb", ENV{ID_TYPE}=="disk", RUN+="/scripts/update-hd-idle.sh"
# sudo udevadm control --reload-rules
# sudo udevadm trigger
# 2) to run on reboot (while a HDD might be attached)
# sudo ln -s /scripts/update-hd-idle.service /etc/systemd/system/update-hd-idle.service
# sudo systemctl enable update-hd-idle.service

CONFIG_FILE="/etc/default/hd-idle"
IDLE_TIME=300   # seconds = 5 minutes

# detect all rotational USB drives connected via USB
drives=$(lsblk -ndo NAME,ROTA,TRAN | awk '$2 == 1 && $3 == "usb" {print $1}')

if [ -z "$drives" ]; then
    echo "No USB HDDs detected, writing minimal config"
    echo 'HD_IDLE_OPTS="-i 0"' > "$CONFIG_FILE"
else
    echo "Detected drives: $drives"

    # build options line
    opts="-i 0"
    for d in $drives; do
        opts="$opts -a /dev/$d -i $IDLE_TIME"
    done

    echo "Writing config: $opts"

    cat > "$CONFIG_FILE" <<EOF
# Autogenerated by $(basename "$0") on $(date)
HD_IDLE_OPTS="$opts"
EOF
fi

# restart hd-idle outside of udev sandbox
systemd-run --no-block systemctl restart hd-idle
