[_default]

all = 2
hourly = 7
daily = 30
weekly = 90
monthly = 365
yearly = unlimited

#[tank/VM]
#
#all = 0
#hourly = 0
#daily = 30
#weekly = 90
#monthly = 365
#yearly = unlimited

#[ssd1]

#recursive = false

#[ssd1/docker]

#ignore = true
