#!/bin/bash
#defaults go here
helptext="starts the VirtualBox VM Win10Server and shuts it down 1 h later.
requires root privileges.
 usage: "$0""

#load defaults
source /scripts/lib/scriptbootstrapper.bsh "$@" --lock
source /scripts/lib/call.bsh

sudo -u user76 VBoxManage startvm "Win10Server" --type headless || true
now
info 3 sleeping for 1 h ...
sleep 1h
c=0
while [[ $( sudo -u user76 vboxmanage showvminfo Win10Server | grep -c "running (since" ) -ge 1 ]]; do
    info 3 shutting down VM...
    sudo -u user76 vboxmanage controlvm "Win10Server" acpipowerbutton
    sleep 1m
    c=$((c+1))
    if [[ "$c" -ge 10 ]]; then
	warning "VirtualBox did not shut down gracefully. Attempting poweroff..."
	sudo -u user76 vboxmanage controlvm "Win10Server" poweroff soft
    fi
done
info 3 done
